### ISSUE TITLE
라이센스 문의드려요..!

### ISSUE THREAD

**Issue by alstn2468** [mingrammer/python-curses-scroll-example#1]
파이썬 공부하는 용도로 제 레파지토리에
같은 내용의 코드를 제가 작성해서 넣으려 하는데
원본 출처를 적으면 혹시 제가 코드를 사용해도
괜찮을까요..? 리드미같은거는 제가 다시 작성할
예정입니다!

**Comment by mingrammer** [comment]
안녕하세요. 네 원본 출처만 적어주시면 감사하겠습니다 :)

혹시나 도움 되실까하여 관련 내용 한국어 포스팅도 첨부드립니다!

https://mingrammer.com/how-to-implement-the-scroll-and-paging-in-python-curses/

**Comment by mingrammer** [comment]
라이센스는 MIT로 셋업해놨습니다 ~

**Comment by alstn2468** [comment]
감사합니다!^^
